name: UI Automation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:    # ✅ allows you to run manually from GitHub Actions tab
  schedule:
    - cron: '*/5 * * * *' # ✅ runs every day at 03:00 UTC (you can change this)

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Tests
        run: mvn clean test -Dbrowser=chrome

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports
