name: UI Automation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Run Tests
        run: mvn clean test

      - name: Upload Test Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports

      - name: Archive Extent Report
        if: success()
        run: |
          mkdir -p artifacts
          cp target/extent-report.html artifacts/

      - name: Send Email with Extent Report
        if: success()
        uses: devops-actions/email@v1
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.AUTOMATION }}
          subject: "✅ UI Automation Test Report"
          to: madaneganesh80@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: |
            Hello Team,

            The UI automation tests have completed successfully.
            Please find the attached Extent Report for details.

          attachments: artifacts/extent-report.html
